name: Build ISO on Debian 12 AMD64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: debian:bookworm-slim
        options: >-
          --privileged
          --name debian
        ports:
          - 8080:8080
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Build ISO on Debian 12
      run: |
        apt-get update
