name: Build ISO on Debian 12 AMD64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: debian:bookworm-slim
        options: >-
          --privileged
          --name debian
        ports:
          - 8080:8080
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: gershwin-root-archive
        github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
        repository: gershwin-os/root
        run-id: 1
    - name: Display structure of downloaded files
      run: ls -R
    - name: Install packages for workflow
      run: |
        apt-get update
        apt install -y unzip
    - name: Build ISO on Debian 12
      run: |
        ls -la
        du -h -s *
